# PyTorch

For working with neural networks, we require a dedicated library due to a number of reasons:

- Abstraction for the NN implementation
- Proper Support for Autograd (for backpropagation)
- Support for different optimizers and other auxiliary NN techniques, etc.

Luckily, PyTorch provides plenty of these features. Actually, PyTorch is based on the classical Torch library implemented in Lua (used to be popular before Tensorflow came in 2015).

We can simply import it as:

In [1]:
import torch

## Tensors

Similar to NumPy's arrays or JAX's NumPy arrays, PyTorch's building blocks are tensors. A tensor is nothing but a generalization of a matrix in higher dimensions.

Similar to JAX's arrays, PyTorch tensors can also run on the GPUs, making them the ultimate choice for Deep Learning.

### Creation from Python Collections

We can initialize a tensor as:

`<tensor> = torch.tensor(<collection>)`

Lets try it. I am as anxious as you.

In [2]:
listA = [1, 2, 3]
setB = {2,4,6}
tupleC = (1,3,5)

In [3]:
tensorA = torch.tensor(listA)
tensorA

tensor([1, 2, 3])

Its type would be:

In [4]:
type(tensorA)

torch.Tensor

PyTorch doesn't work with sets as well (as we saw for the JAX).

In [5]:
tensorB = torch.tensor(setB)


RuntimeError: ignored

In [6]:
tensorC = torch.tensor(tupleC)
tensorC

tensor([1, 3, 5])

### From NumPy Arrays

Similarly, we can also make them using the (more useful, versatile) NumPy arrays.

In [9]:
import numpy as np

npA = np.arange(1,10)

tensorD = torch.tensor(npA)
tensorD

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

Is there any difference in the type? No!

In [10]:
type(tensorD)

torch.Tensor

### Intrinsic Creation

Just like we saw how we can initialize NumPy (or JAX) arrays from the scratch with some built-in functions, we can do the same for the tensors as well.

Like:

- `ones()`
- `zeros()`

**Note:** They take `<shape>` as the argument.

In [14]:
tensorE = torch.ones((3,3))
tensorE

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
tensorF = torch.zeros((3,4))
tensorF

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

**Note:** If you feel comfortable with NumPy arrays, you can always make an intrinsic NumPy array and convert it into a tensor.

### Attributes

We saw above that `type()` of all tensors is same. Though, similar to the JAX arrays, they can have different datatype (`dtype`).

We have following common attributes for a tensor:

- `dtype`
- `shape`
- `device` – CPU or GPU

In [16]:
tensorF.device

device(type='cpu')

In [17]:
tensorF.dtype

torch.float32

**Note:** It doesn't work on JAX arrays yet. Things may change in the future with Keras 3.0. Can verify it by uncommenting the cell below.

In [7]:
"""
import jax
import jax.numpy as jnp

jnpA = jnp.array(listA)
tensorD = torch.tensor(jnpA) #Uncomment it to check the error

"""

Array([1, 2, 3], dtype=int32)

### Broadcasting

Broadcasting is one of the confusing aspect of Numerical computing being inconsistent with the Linear Algebra.

## AutoDiff

Similar to JAX, PyTorch also has a strong auto-differentiation unit.

--To Be COntinued---

## Recommended Resources

- [Microsoft Learn – PyTorch Fundamentals](https://learn.microsoft.com/en-us/training/paths/pytorch-fundamentals/)